package day37coding;
public class DAY37CODING {

    public static void main(String[] args) {
      int a=2;
      int b=4;
      
      //pengisian nilai
      a = b; // a sekarang nilai nya 4
     
      //pengisian dan penambahan
      a +=b;
      //pengisian dan pengurangan
      a -=b;
      
        System.out.println("nilai a setelah penambahan: " + a);
        System.out.println("nilai a setelah pengurangan: " + a);
    }    
}
