package day4coding;
public class DAY4CODING {
 public static void main(String[] args) {

     //System.out.print(""); digunakan untuk menampilkan/mencetak output ke konsol 
     //atau terminal,contoh menampilkan "Hello my friend"
     System.out.print("menampilkan output pada kodingan");
     System.out.print("Hello my friend");
     
     //System.out.printf akan mencetak string "Nama saya adalah Awanda 
     //dan umur saya adalah 20 tahun".
     // dengan menggunakan format %s, dan %d.
     System.out.printf("Nama saya adalah %s dan umur saya adalah %d tahun.\n", "Awanda", 20);
    }
    
}
