package day17coding;
public class DAY17CODING {
    public static void main(String[] args) {
       
        char huruf = 'A';
        char huruf1 = 'W';
        char huruf2 = 'A';
        char huruf3 = 'N';
        char huruf4 = 'D';
        char huruf5= 'A';
        
        System.out.print(huruf);
        System.out.print(huruf1);
        System.out.print(huruf2);
        System.out.print(huruf3);
        System.out.print(huruf4);
        System.out.print(huruf5);  
    }  
}
